name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install dependencies
        run: npm ci
      - name: Verify next.config.js
        run: cat next.config.js
      - name: Copy all images to public directory
        run: |
          mkdir -p public/images/icons
          find public -type f -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" -o -name "*.svg" | xargs -I{} ls -la {}
      - name: Build with Next.js
        run: npm run build
      - name: Create .nojekyll file
        run: touch ./out/.nojekyll
      - name: Fix asset paths
        run: |
          echo "Fixing asset paths in the build output..."
          find ./out -type f -name "*.html" -exec grep -l "/_next/" {} \; | xargs -I{} echo "Found _next references in: {}"
      - name: List output directory structure
        run: find ./out -type f | sort
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
